
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navBar";
import MaxWidthWrapper from "@/components/maxWidthWrapper";
import SideNav from "@/components/sideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
         <div className="font-sans w-full flex flex-row transition-transform bg-slate-100 max-screen">
            <SideNav /> 
            {children}
         </div>
      </body>
    </html>
  );
}
